/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author WINDOWS 10
 */
public class DashboardKasir extends javax.swing.JFrame {

    /**
     * Creates new form DashboardKasir
     */
    public DashboardKasir() {
        initComponents();
        sisaStockObat();
        danaPemasukan();
        barangTerjual();
    }
public void sisaStockObat(){
        Logic.Dashboard ds = new Logic.Dashboard();
        int hasil = ds.stockObat();
        String result = String.valueOf(hasil);
        lblStokObat.setText(result);
    }
    public void danaPemasukan(){
        Logic.Dashboard ds = new Logic.Dashboard();
        int hasil = ds.Pemasukan();
        String result = String.valueOf(hasil);
        lblDanaPemasukan.setText(result);
    }
    public void barangTerjual(){
        Logic.Dashboard ds = new Logic.Dashboard();
        int hasil = ds.barangTerjual();
        String result = String.valueOf(hasil);
        lblBarangTerjual.setText(result);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblDanaPemasukan = new javax.swing.JLabel();
        lblBarangTerjual = new javax.swing.JLabel();
        lblStokObat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(550, 620, 70, 22);

        lblDanaPemasukan.setBackground(new java.awt.Color(255, 255, 255));
        lblDanaPemasukan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDanaPemasukan.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblDanaPemasukan);
        lblDanaPemasukan.setBounds(590, 450, 80, 30);

        lblBarangTerjual.setBackground(new java.awt.Color(255, 255, 255));
        lblBarangTerjual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBarangTerjual.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblBarangTerjual);
        lblBarangTerjual.setBounds(1090, 450, 80, 30);

        lblStokObat.setBackground(new java.awt.Color(255, 255, 255));
        lblStokObat.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblStokObat.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblStokObat);
        lblStokObat.setBounds(590, 260, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fahmarevisi kasir.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1366, 768);

        setBounds(0, 0, 1664, 796);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBarangTerjual;
    private javax.swing.JLabel lblDanaPemasukan;
    private javax.swing.JLabel lblStokObat;
    // End of variables declaration//GEN-END:variables
}
