/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.conn;

/**
 *
 * @author WINDOWS 10
 */
public class DetailObatAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DetailObatAdmin
     */
    public DetailObatAdmin() {
        initComponents();
        setDetail();
    }

    public void setDetail(){
        try {
            ObatAdmin obat = new ObatAdmin();
            String sql = "SELECT * FROM obat JOIN detail_obat ON obat.kode_obat = detail_obat.kode_obat WHERE "
                + "detail_obat.id_detail ='"+obat.id_detail+"'";
        Connection koneksi = (Connection)conn.configDB();
        Statement stm = koneksi.createStatement();
        ResultSet res = stm.executeQuery(sql);
        if(res.next()){
            lblKode.setText(res.getString("kode_obat"));
            lblNama.setText(res.getString("nama"));
            lblJenis.setText(res.getString("jenis"));
            lblKategori.setText(res.getString("kategori"));
            lblStok.setText(res.getString("stok"));
            lblDosis.setText(res.getString("dosis"));
            lblHargaJual.setText(res.getString("harga_jual"));
            lblHargaBeli.setText(res.getString("harga_beli"));
            lblTglExp.setText(res.getString("tgl_kadaluarsa"));
            lblTglMasuk.setText(res.getString("tgl_masuk"));
            lblKet.setText(res.getString("keterangan"));  
            lblDiskon.setText(res.getString("diskon"));
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKet = new javax.swing.JLabel();
        lblKode = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblJenis = new javax.swing.JLabel();
        lblHargaBeli = new javax.swing.JLabel();
        lblDosis = new javax.swing.JLabel();
        lblTglExp = new javax.swing.JLabel();
        lblTglMasuk = new javax.swing.JLabel();
        lblStok = new javax.swing.JLabel();
        lblDiskon = new javax.swing.JLabel();
        lblHargaJual = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();
        btnKembali = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblKet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblKet);
        lblKet.setBounds(500, 430, 280, 170);

        lblKode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblKode);
        lblKode.setBounds(500, 160, 250, 40);

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblNama);
        lblNama.setBounds(500, 220, 250, 40);

        lblJenis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblJenis);
        lblJenis.setBounds(500, 270, 250, 40);

        lblHargaBeli.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblHargaBeli);
        lblHargaBeli.setBounds(500, 330, 250, 40);

        lblDosis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblDosis);
        lblDosis.setBounds(500, 380, 250, 40);

        lblTglExp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblTglExp);
        lblTglExp.setBounds(1050, 160, 250, 40);

        lblTglMasuk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblTglMasuk);
        lblTglMasuk.setBounds(1050, 210, 250, 40);

        lblStok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblStok);
        lblStok.setBounds(1050, 270, 250, 40);

        lblDiskon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblDiskon);
        lblDiskon.setBounds(1050, 430, 250, 40);

        lblHargaJual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblHargaJual);
        lblHargaJual.setBounds(1050, 430, 250, 40);

        lblKategori.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblKategori);
        lblKategori.setBounds(1050, 330, 250, 40);

        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });
        getContentPane().add(btnKembali);
        btnKembali.setBounds(320, 570, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/detail obat.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        setBounds(0, 0, 1598, 882);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        ObatAdmin obat = new ObatAdmin();
        obat.id_detail = 0;
        obat.kd_obat = 0;
        this.setVisible(false);
        obat.setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailObatAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblDosis;
    private javax.swing.JLabel lblHargaBeli;
    private javax.swing.JLabel lblHargaJual;
    private javax.swing.JLabel lblJenis;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblKet;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblStok;
    private javax.swing.JLabel lblTglExp;
    private javax.swing.JLabel lblTglMasuk;
    // End of variables declaration//GEN-END:variables
}
