/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Logic.Obat;
import Logic.login;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.conn;
/**
 *
 * @author WINDOWS 10
 */
public class EditObatAdmin extends javax.swing.JFrame {
login lg = new login();
    /**
     * Creates new form EditObatAdmin
     */
    public EditObatAdmin() {
        initComponents();
        setData();
    }
    
    public void setData(){
        lblNama1.setText(lg.nama);
        try {
            ObatAdmin obat = new ObatAdmin();
            String sql = "SELECT * FROM obat JOIN detail_obat ON obat.kode_obat = detail_obat.kode_obat WHERE "
                + "detail_obat.id_detail ='"+obat.id_detail+"'";
        Connection koneksi = (Connection)conn.configDB();
        Statement stm = koneksi.createStatement();
        ResultSet res = stm.executeQuery(sql);
        if(res.next()){
            lblKode.setText(res.getString("kode_obat"));
            txtNama.setText(res.getString("nama"));
            cmbJenis.setSelectedItem(res.getString("jenis"));
            cmbKategori.setSelectedItem(res.getString("kategori"));
            txtStok.setText(res.getString("stok"));
            txtDosis.setText(res.getString("dosis"));
            txtHargaJual.setText(res.getString("harga_jual"));
            txtHargaBeli.setText(res.getString("harga_beli"));
            txtTglExp.setText(res.getString("tgl_kadaluarsa"));
            txtKet.setText(res.getString("keterangan"));  
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKode = new javax.swing.JLabel();
        txtTglExp = new javax.swing.JTextField();
        cmbKategori = new javax.swing.JComboBox<>();
        cmbJenis = new javax.swing.JComboBox<>();
        txtNama = new javax.swing.JTextField();
        txtDosis = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKet = new javax.swing.JTextArea();
        btnKembali = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JLabel();
        cmbUser = new javax.swing.JComboBox<>();
        lblNama1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblKode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblKode);
        lblKode.setBounds(530, 130, 130, 40);

        txtTglExp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTglExp.setBorder(null);
        getContentPane().add(txtTglExp);
        txtTglExp.setBounds(1090, 130, 240, 40);

        cmbKategori.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Obat BebasTerbatas", "Obat Bebas", "Obat Keras", "Obat Wajib Apotek", "Obat Gol Narkotika", "Obat Psikotropika", "Obat Herbal", " " }));
        getContentPane().add(cmbKategori);
        cmbKategori.setBounds(530, 260, 250, 30);

        cmbJenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet", "Cair", "Kapsul", "Oles", "Suntik", "Implam" }));
        getContentPane().add(cmbJenis);
        cmbJenis.setBounds(530, 320, 250, 30);

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNama.setBorder(null);
        getContentPane().add(txtNama);
        txtNama.setBounds(530, 190, 250, 30);

        txtDosis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDosis.setBorder(null);
        getContentPane().add(txtDosis);
        txtDosis.setBounds(530, 380, 250, 30);

        txtHargaJual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHargaJual.setBorder(null);
        getContentPane().add(txtHargaJual);
        txtHargaJual.setBounds(1090, 310, 240, 40);

        txtHargaBeli.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHargaBeli.setBorder(null);
        getContentPane().add(txtHargaBeli);
        txtHargaBeli.setBounds(1090, 250, 240, 40);

        txtStok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtStok.setBorder(null);
        getContentPane().add(txtStok);
        txtStok.setBounds(1090, 190, 240, 30);

        txtKet.setColumns(20);
        txtKet.setRows(5);
        txtKet.setBorder(null);
        jScrollPane1.setViewportView(txtKet);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 470, 800, 130);

        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });
        getContentPane().add(btnKembali);
        btnKembali.setBounds(350, 660, 150, 50);

        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(530, 660, 150, 40);

        cmbUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Menu----", "Profil", "Logout" }));
        cmbUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserActionPerformed(evt);
            }
        });
        getContentPane().add(cmbUser);
        cmbUser.setBounds(1140, 50, 130, 26);

        lblNama1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNama1.setText("jLabel2");
        getContentPane().add(lblNama1);
        lblNama1.setBounds(1140, 10, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Edit obat.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        setBounds(0, 0, 1595, 891);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        ObatAdmin obat = new ObatAdmin();
        obat.id_detail = 0;
        obat.kd_obat = 0;
        this.setVisible(false);
        obat.setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
         String nama = txtNama.getText();
        String jenis = String.valueOf(cmbJenis.getSelectedItem());
        String kategori = String.valueOf(cmbKategori.getSelectedItem());
        String stok = txtStok.getText();
        String dosis = txtDosis.getText();
        String harga_jual = txtHargaJual.getText();
        String harga_beli = txtHargaBeli.getText();
        String tgl_exp = txtTglExp.getText();
        String ket = txtKet.getText();
        Obat obat = new Obat();
        Boolean edit = obat.edit(ObatAdmin.kd_obat, nama, jenis, kategori, stok, dosis, harga_beli, harga_jual, tgl_exp, ket);
        if(edit){
            JOptionPane.showMessageDialog(rootPane, "Data berhasil di Update");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Data gagal di Update");
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void cmbUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserActionPerformed
        String menu = String.valueOf(cmbUser.getSelectedItem());
        switch(menu){
            case "Profil":
            this.setVisible(false);
            this.dispose();
            new ProfilUser().setVisible(true);
            break;
            case "Logout":
            this.setVisible(false);
            this.dispose();
            lg.logOut();
            break;
        }
    }//GEN-LAST:event_cmbUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditObatAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnKembali;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JComboBox<String> cmbUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblNama1;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextArea txtKet;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTglExp;
    // End of variables declaration//GEN-END:variables
}
