/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Logic.Util;
import Logic.Dashboard;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.conn;

/**
 *
 * @author WINDOWS 10
 */
public class KeuntunganDanPemasukan extends javax.swing.JFrame {
    Util util = new Util();
    Dashboard db = new Dashboard();
    /**
     * Creates new form KeuntunganDanPemasukan
     */
    public KeuntunganDanPemasukan() {
        initComponents();
        load_table();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setUndecorated(true);
        this.setVisible(true);
    }
    
    public void load_table(){
            DefaultTableModel model = new DefaultTableModel();      
            model.addColumn("Kode Transaksi");
            model.addColumn("Tanggal Transaksi");
            model.addColumn("Nama");
            model.addColumn("Harga Jual");
            model.addColumn("Harga Beli");
            model.addColumn("Keuntungan");
        try{
            int no = 1;
        String sql = "SELECT detail_transaksi.kode_transaksi,tgl_transaksi,nama,harga_jual,harga_beli,(harga_jual-harga_beli) AS keuntungan FROM detail_transaksi JOIN transaksi ON detail_transaksi.kode_transaksi JOIN obat ON detail_transaksi.kode_obat = obat.kode_obat JOIN detail_obat ON detail_transaksi.id_detail_obat = detail_obat.id_detail ";
        Connection koneksi = (Connection)conn.configDB();
        Statement stm = koneksi.createStatement();
        ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{
                    res.getString("kode_transaksi"),
                    res.getString("tgl_transaksi"), 
                    res.getString("nama"),
                    res.getString("harga_jual"), 
                    res.getString("harga_beli"), 
                    res.getString("keuntungan"),
                });
            }
            table.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        }
    
     public void load_table_waktu(String dateStart,String dateEnd){
            DefaultTableModel model = new DefaultTableModel();      
            model.addColumn("Kode Transaksi");
            model.addColumn("Tanggal Transaksi");
            model.addColumn("Nama");
            model.addColumn("Harga Jual");
            model.addColumn("Harga Beli");
            model.addColumn("Keuntungan");
        try{
            int no = 1;
        String sql = "SELECT detail_transaksi.kode_transaksi,tgl_transaksi,nama,harga_jual,harga_beli,(harga_jual-harga_beli) AS keuntungan FROM detail_transaksi JOIN transaksi ON detail_transaksi.kode_transaksi JOIN obat ON detail_transaksi.kode_obat = obat.kode_obat JOIN detail_obat ON detail_transaksi.id_detail_obat = detail_obat.id_detail WHERE tgl_transaksi BETWEEN '"+dateStart+"' AND '"+dateEnd+"'";
        Connection koneksi = (Connection)conn.configDB();
        Statement stm = koneksi.createStatement();
        ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{
                    res.getString("kode_transaksi"),
                    res.getString("tgl_transaksi"), 
                    res.getString("nama"),
                    res.getString("harga_jual"), 
                    res.getString("harga_beli"), 
                    res.getString("keuntungan"),
                });
            }
            table.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        }
    
     
    public void setData(String dateStart, String dateEnd){
        String pemasukan = String.valueOf(db.Pemasukan(dateStart, dateEnd));
        String keuntungan = String.valueOf(db.labaBersih(dateStart, dateEnd));
        lblKeuntungan.setText(keuntungan);
        lblPemasukan.setText(pemasukan);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        txtDateEnd = new javax.swing.JTextField();
        txtDateStart = new javax.swing.JTextField();
        cmbWaktu = new javax.swing.JComboBox<>();
        lblKeuntungan = new javax.swing.JLabel();
        lblPemasukan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setRowHeight(40);
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 252, 1010, 410);

        txtCari.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCari.setBorder(null);
        getContentPane().add(txtCari);
        txtCari.setBounds(340, 170, 260, 30);

        txtDateEnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDateEnd.setBorder(null);
        getContentPane().add(txtDateEnd);
        txtDateEnd.setBounds(1030, 170, 160, 30);

        txtDateStart.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDateStart.setBorder(null);
        getContentPane().add(txtDateStart);
        txtDateStart.setBounds(790, 170, 160, 30);

        cmbWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------Pilih Waktu------", "Hari", "Bulan" }));
        cmbWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbWaktuActionPerformed(evt);
            }
        });
        getContentPane().add(cmbWaktu);
        cmbWaktu.setBounds(780, 120, 190, 40);

        lblKeuntungan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblKeuntungan);
        lblKeuntungan.setBounds(980, 690, 190, 40);

        lblPemasukan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblPemasukan);
        lblPemasukan.setBounds(490, 690, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pemasukan dan keuntungan.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1407, 768);

        setBounds(0, 0, 1554, 894);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbWaktuActionPerformed
        String waktu = String.valueOf(cmbWaktu.getSelectedItem());
        if(waktu.equals("Hari")){
            String dateStart = util.dateStart();
            String dateEnd = util.dateEnd();
            load_table_waktu(dateStart, dateEnd);
            setData(dateStart, dateEnd);
            txtDateStart.setText(dateStart);
            txtDateEnd.setText(dateEnd);
        }else if(waktu.equals("Bulan")){
            String dateStart = util.dateMonthAgo();
            String dateEnd = util.date();
            load_table_waktu(dateStart, dateEnd);
            setData(dateStart, dateEnd);
            txtDateStart.setText(dateStart);
            txtDateEnd.setText(dateEnd);
        }

    }//GEN-LAST:event_cmbWaktuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeuntunganDanPemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeuntunganDanPemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeuntunganDanPemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeuntunganDanPemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeuntunganDanPemasukan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbWaktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKeuntungan;
    private javax.swing.JLabel lblPemasukan;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtDateEnd;
    private javax.swing.JTextField txtDateStart;
    // End of variables declaration//GEN-END:variables
}
