/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Logic.Dashboard;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.conn;

/**
 *
 * @author WINDOWS 10
 */
public class ObatExp extends javax.swing.JFrame {

 
    
    
    
    public ObatExp() {
        initComponents();
        load_table();
        loadDate();
    }

    public void load_table(){
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("No");      
                model.addColumn("Kode Obat");
                model.addColumn("Nama");
                model.addColumn("Kategori");
                model.addColumn("Jenis");
                model.addColumn("Stok");
                model.addColumn("Diskon");
                model.addColumn("Harga Jual");
            try{
                Dashboard db = new Dashboard();
                int no = 1;
                String sql = "SELECT * FROM obat JOIN detail_obat ON obat.kode_obat = detail_obat.kode_obat WHERE tgl_kadaluarsa BETWEEN '"+db.date()+"' AND '"+db.dateExp()+"' ";
                Connection conn = (Connection) koneksi.conn.configDB();
                Statement stm = conn.createStatement();
                ResultSet res = stm.executeQuery(sql);
                while(res.next()){
                    model.addRow(new Object[]{
                        no++,
                        res.getString("id_detail"),
                        res.getString("nama"),
                        res.getString("kategori"),
                        res.getString("jenis"),
                        res.getString("stok"), 
                        res.getString("diskon"), 
                        res.getString("harga_jual"),
                    });
                }
                table.setModel(model);
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }
    
    public void loadDate(){
        Dashboard db = new Dashboard();
        lblDateStart.setText(db.date());
        lblDateEnd.setText(db.dateExp());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAutoGenerate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        BtnAutoGenerate = new javax.swing.JLabel();
        txtRentangWaktu = new javax.swing.JTextField();
        lblTotalDiskon = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblDateEnd = new javax.swing.JLabel();
        lblDateStart = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtAutoGenerate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAutoGenerate.setBorder(null);
        txtAutoGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutoGenerateActionPerformed(evt);
            }
        });
        getContentPane().add(txtAutoGenerate);
        txtAutoGenerate.setBounds(1050, 260, 70, 20);

        table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setRowHeight(40);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 460, 1030, 260);

        BtnAutoGenerate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAutoGenerateMouseClicked(evt);
            }
        });
        getContentPane().add(BtnAutoGenerate);
        BtnAutoGenerate.setBounds(1190, 260, 120, 50);

        txtRentangWaktu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRentangWaktu.setBorder(null);
        getContentPane().add(txtRentangWaktu);
        txtRentangWaktu.setBounds(1140, 140, 70, 20);

        lblTotalDiskon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblTotalDiskon);
        lblTotalDiskon.setBounds(530, 370, 130, 20);

        lblHarga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblHarga);
        lblHarga.setBounds(480, 260, 130, 30);

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblNama);
        lblNama.setBounds(480, 210, 130, 30);

        lblDateEnd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblDateEnd);
        lblDateEnd.setBounds(610, 130, 130, 30);

        lblDateStart.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(lblDateStart);
        lblDateStart.setBounds(440, 130, 130, 30);

        txtDiskon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDiskon.setBorder(null);
        txtDiskon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiskonKeyReleased(evt);
            }
        });
        getContentPane().add(txtDiskon);
        txtDiskon.setBounds(504, 310, 70, 30);

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSearch.setBorder(null);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch);
        txtSearch.setBounds(890, 360, 180, 30);

        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1227, 140, 50, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Order baru", "Tanggal Awal", "Tanggal Akhir" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(1130, 360, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporan obat exprevisi  (4).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 768);

        setBounds(0, 0, 1591, 877);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAutoGenerateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAutoGenerateMouseClicked
              int diskon = Integer.parseInt(txtAutoGenerate.getText());
        try {
            Dashboard db = new Dashboard();
             String sql = "SELECT * FROM obat JOIN detail_obat ON obat.kode_obat = detail_obat.kode_obat WHERE tgl_kadaluarsa BETWEEN '"+db.date()+"' AND '"+db.dateExp()+"' ";
                Connection conn = (Connection) koneksi.conn.configDB();
                Statement stm = conn.createStatement();
                ResultSet res = stm.executeQuery(sql);
                while (res.next()) {
                    if(res.getInt("diskon") == 0){
                    int harga = res.getInt("harga_jual");
                    int hasil = harga * diskon / 100;
                    String queryDiskon = "UPDATE detail_obat SET diskon = '" + hasil + "' WHERE id_detail ='" + res.getInt("id_detail") + "'";
                    PreparedStatement pstHapusDetail = conn.prepareStatement(queryDiskon);
                    pstHapusDetail.execute();
                      
                }  
                }
//                stm.close();
                JOptionPane.showMessageDialog(rootPane, "Data berhasil di Update");
                load_table();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_BtnAutoGenerateMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String search = txtSearch.getText();
        DefaultTableModel model = new DefaultTableModel();
                model.addColumn("No");      
                model.addColumn("Kode Obat");
                model.addColumn("Nama");
                model.addColumn("Kategori");
                model.addColumn("Jenis");
                model.addColumn("Stok");
                model.addColumn("Diskon");
                model.addColumn("Harga Jual");
            try{
                Dashboard db = new Dashboard();
                int no = 1;
                String sql = "SELECT * FROM obat JOIN detail_obat ON obat.kode_obat = detail_obat.kode_obat WHERE nama LIKE '%"+search+"%' AND tgl_kadaluarsa BETWEEN '"+db.date()+"' AND '"+db.dateExp()+"'";
                Connection conn = (Connection) koneksi.conn.configDB();
                Statement stm = conn.createStatement();
                ResultSet res = stm.executeQuery(sql);
                while(res.next()){
                    model.addRow(new Object[]{
                        no++,
                        res.getString("kode_obat"),
                        res.getString("nama"),
                        res.getString("kategori"),
                        res.getString("jenis"),
                        res.getString("stok"), 
                        res.getString("diskon"), 
                        res.getString("harga_jual"),
                    });
                }
                table.setModel(model);
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }

    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtAutoGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutoGenerateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutoGenerateActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtDiskonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiskonKeyReleased
        
    }//GEN-LAST:event_txtDiskonKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int rentangWaktu = Integer.parseInt(txtRentangWaktu.getText());
        Dashboard db = new Dashboard();
        db.rentangWaktu = rentangWaktu;
        lblDateStart.setText(db.date());
        lblDateEnd.setText(db.dateExp());
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int baris = table.rowAtPoint(evt.getPoint());
        String diskon = table.getValueAt(baris, 7).toString();
        String harga = table.getValueAt(baris, 8).toString();
        txtSearch.setText(diskon);
    }//GEN-LAST:event_tableMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObatExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObatExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObatExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObatExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObatExp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnAutoGenerate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDateEnd;
    private javax.swing.JLabel lblDateStart;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTotalDiskon;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtAutoGenerate;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtRentangWaktu;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
