/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Logic.Dashboard;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.conn;

/**
 *
 * @author WINDOWS 10
 */
public class ObatExp extends javax.swing.JFrame {

 
    
    
    
    public ObatExp() {
        initComponents();
        load_table();
    }
    public void load_table(){
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("No");      
                model.addColumn("Kode Obat");
                model.addColumn("Nama");
                model.addColumn("Kategori");
                model.addColumn("Jenis");
                model.addColumn("Stok");
                model.addColumn("Diskon");
                model.addColumn("Harga Jual");
            try{
                Dashboard db = new Dashboard();
                int no = 1;
                String sql = "SELECT * FROM obat JOIN detail_obat ON obat.kode_obat = detail_obat.kode_obat WHERE tgl_kadaluarsa BETWEEN '"+db.date()+"' AND '"+db.dateExp()+"' ";
                Connection conn = (Connection) koneksi.conn.configDB();
                Statement stm = conn.createStatement();
                ResultSet res = stm.executeQuery(sql);
                while(res.next()){
                    model.addRow(new Object[]{
                        no++,
                        res.getString("kode_obat"),
                        res.getString("nama"),
                        res.getString("kategori"),
                        res.getString("jenis"),
                        res.getString("stok"), 
                        res.getString("diskon"), 
                        res.getString("harga_jual"),
                    });
                }
                table.setModel(model);
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
            }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDiskon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtDiskon);
        txtDiskon.setBounds(410, 160, 150, 22);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 210, 510, 402);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah);
        btnTambah.setBounds(590, 160, 73, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporan obat exprevisi .jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1407, 768);

        setBounds(0, 0, 1591, 877);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
                int diskon = Integer.parseInt(txtDiskon.getText());
        try {
            Dashboard db = new Dashboard();
             String sql = "SELECT * FROM obat JOIN detail_obat ON obat.kode_obat = detail_obat.kode_obat WHERE tgl_kadaluarsa BETWEEN '"+db.date()+"' AND '"+db.dateExp()+"' ";
                Connection conn = (Connection) koneksi.conn.configDB();
                Statement stm = conn.createStatement();
                ResultSet res = stm.executeQuery(sql);
                while (res.next()) {
                    if(res.getInt("diskon") == 0){
                    int harga = res.getInt("harga_jual");
                    int hasil = harga * diskon / 100;
                    String queryDiskon = "UPDATE detail_obat SET diskon = '" + hasil + "' WHERE id_detail ='" + res.getInt("id_detail") + "'";
                    PreparedStatement pstHapusDetail = conn.prepareStatement(queryDiskon);
                    pstHapusDetail.execute();
                      
                }  
                }
//                stm.close();
                JOptionPane.showMessageDialog(rootPane, "Data berhasil di Update");
                load_table();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnTambahActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObatExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObatExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObatExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObatExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObatExp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtDiskon;
    // End of variables declaration//GEN-END:variables
}
