/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Logic.Obat;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.conn;
/**
 *
 * @author WINDOWS 10
 */
public class ObatAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ObatAdmin
     */
    public static int kd_obat;
    public static int id_detail;
    public ObatAdmin() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setUndecorated(true);
        this.setVisible(true);
        load_table();
    }
public void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");      
        model.addColumn("Kode Obat");
        model.addColumn("id_detail");
        model.addColumn("Nama");
        model.addColumn("Kategori");
        model.addColumn("Jenis");
        model.addColumn("Stok");
        model.addColumn("Harga Jual");
    try{
        int no = 1;
        String sql = "SELECT * FROM obat JOIN detail_obat ON obat.kode_obat = detail_obat.kode_obat";
        Connection conn = (Connection) koneksi.conn.configDB();
        Statement stm = conn.createStatement();
        ResultSet res = stm.executeQuery(sql);
        while(res.next()){
            model.addRow(new Object[]{
                no++,
                res.getString("kode_obat"),
                res.getString("id_detail"),
                res.getString("nama"),
                res.getString("kategori"), 
                res.getString("jenis"), 
                res.getString("stok"), 
                res.getString("harga_jual"),
            });
        }
        table.setModel(model);
    }catch(Exception e){
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnDetail = new javax.swing.JLabel();
        btnHapus = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        cmbJenis = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 170, 140, 40);

        table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setRowHeight(50);
        table.setRowMargin(10);
        table.setSelectionBackground(new java.awt.Color(0, 15, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 330, 960, 402);

        btnDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDetailMouseClicked(evt);
            }
        });
        getContentPane().add(btnDetail);
        btnDetail.setBounds(440, 230, 140, 40);

        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        getContentPane().add(btnHapus);
        btnHapus.setBounds(610, 160, 150, 50);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(610, 220, 150, 50);

        txtCari.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCari.setBorder(null);
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });
        getContentPane().add(txtCari);
        txtCari.setBounds(890, 240, 360, 30);

        cmbJenis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet", "Cair", "Kapsul", "Oles", "Suntik", "Implam" }));
        getContentPane().add(cmbJenis);
        cmbJenis.setBounds(980, 180, 170, 40);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1170, 170, 90, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/obatnew.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1407, 768);

        setBounds(0, 0, 1604, 869);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(kd_obat == 0){
            this.setVisible(false);
            new TambahObatAdmin().setVisible(true);
        }else{
            this.setVisible(false);
            new TambahDetailObatAdmin().setVisible(true);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int baris = table.rowAtPoint(evt.getPoint());
        String kode_obat = table.getValueAt(baris, 1).toString();
        int result = Integer.parseInt(kode_obat);  
        String detail = table.getValueAt(baris, 2).toString();
        int resultDetail = Integer.parseInt(detail);
        System.out.println(kd_obat);
        kd_obat = result;
        id_detail = resultDetail;
    }//GEN-LAST:event_tableMouseClicked

    private void btnDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDetailMouseClicked
        this.setVisible(false);
        new DetailObatAdmin().setVisible(true);
    }//GEN-LAST:event_btnDetailMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        Obat obat = new Obat();
        boolean result = obat.hapus(kd_obat);
        if(result){
            JOptionPane.showMessageDialog(rootPane, "Data berhasil di hapus");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Data gagal di hapus");
        }
        kd_obat = 0; 
        id_detail = 0;
        load_table();
    }//GEN-LAST:event_btnHapusMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setVisible(false);
        new EditObatAdmin().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        String cari = txtCari.getText();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");      
        model.addColumn("Kode Obat");
        model.addColumn("id_detail");   
        model.addColumn("Nama");
        model.addColumn("Kategori");
        model.addColumn("Jenis");
        model.addColumn("Stok");
        model.addColumn("Harga Jual");
    try{
        int no = 1;
        String sql = "SELECT * FROM obat JOIN detail_obat ON obat.kode_obat = detail_obat.kode_obat WHERE nama LIKE '%"+cari+"%'";
        Connection conn = (Connection) koneksi.conn.configDB();
        Statement stm = conn.createStatement();
        ResultSet res = stm.executeQuery(sql);
        while(res.next()){
            model.addRow(new Object[]{
                no++,
                res.getString("kode_obat"),
                res.getString("id_detail"),
                res.getString("nama"),
                res.getString("kategori"), 
                res.getString("jenis"), 
                res.getString("stok"), 
                res.getString("harga_jual"),
            });
        }
        table.setModel(model);
    }catch(Exception e){
    }
    
    }//GEN-LAST:event_txtCariKeyPressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        String jenis = String.valueOf(cmbJenis.getSelectedItem());
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");      
        model.addColumn("Kode Obat");
        model.addColumn("id_detail");   
        model.addColumn("Nama");
        model.addColumn("Kategori");
        model.addColumn("Jenis");
        model.addColumn("Stok");
        model.addColumn("Harga Jual");
    try{
        int no = 1;
        String sql = "SELECT * FROM obat JOIN detail_obat ON obat.kode_obat = detail_obat.kode_obat WHERE jenis = '"+jenis+"'";
        Connection conn = (Connection) koneksi.conn.configDB();
        Statement stm = conn.createStatement();
        ResultSet res = stm.executeQuery(sql);
        while(res.next()){
            model.addRow(new Object[]{
                no++,
                res.getString("kode_obat"),
                res.getString("id_detail"),
                res.getString("nama"),
                res.getString("kategori"), 
                res.getString("jenis"), 
                res.getString("stok"), 
                res.getString("harga_jual"),
            });
        }
        table.setModel(model);
    }catch(Exception e){
    }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObatAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDetail;
    private javax.swing.JLabel btnHapus;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
