/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Logic.Obat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS 10
 */
public class TambahObatAdmin extends javax.swing.JFrame {

    /**
     * Creates new form TambahObatAdmin
     */
    public TambahObatAdmin() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setUndecorated(true);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtDosis = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        txtTglexp = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbJenis = new javax.swing.JComboBox<>();
        cmbKategori = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKet = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });
        getContentPane().add(btnKembali);
        btnKembali.setBounds(350, 590, 150, 40);

        txtStok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtStok.setBorder(null);
        txtStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokActionPerformed(evt);
            }
        });
        getContentPane().add(txtStok);
        txtStok.setBounds(1080, 190, 250, 30);

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNama.setBorder(null);
        getContentPane().add(txtNama);
        txtNama.setBounds(530, 130, 250, 40);

        txtDosis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDosis.setBorder(null);
        getContentPane().add(txtDosis);
        txtDosis.setBounds(530, 320, 250, 40);

        txtHargaJual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHargaJual.setBorder(null);
        getContentPane().add(txtHargaJual);
        txtHargaJual.setBounds(1080, 310, 250, 40);

        txtTglexp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTglexp.setBorder(null);
        getContentPane().add(txtTglexp);
        txtTglexp.setBounds(1080, 130, 250, 40);

        txtHargaBeli.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHargaBeli.setBorder(null);
        getContentPane().add(txtHargaBeli);
        txtHargaBeli.setBounds(1080, 250, 250, 40);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 590, 150, 40);

        cmbJenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet", "Cair", "Kapsul", "Oles", "Suntik", "Implam" }));
        getContentPane().add(cmbJenis);
        cmbJenis.setBounds(520, 260, 260, 30);

        cmbKategori.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Obat BebasTerbatas", "Obat Bebas", "Obat Keras", "Obat Wajib Apotek", "Obat Gol Narkotika", "Obat Psikotropika", "Obat Herbal", " " }));
        getContentPane().add(cmbKategori);
        cmbKategori.setBounds(520, 200, 260, 30);

        txtKet.setColumns(20);
        txtKet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtKet.setRows(5);
        txtKet.setBorder(null);
        jScrollPane1.setViewportView(txtKet);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 390, 800, 140);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tambahobatnew.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1407, 768);

        setBounds(0, 0, 1601, 888);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        ObatAdmin obat = new ObatAdmin();
        obat.kd_obat = 0;
        this.setVisible(false);
        obat.setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String nama = txtNama.getText();
        String jenis = String.valueOf(cmbJenis.getSelectedItem());
        String kategori = String.valueOf(cmbKategori.getSelectedItem());
        String stok = txtStok.getText();
        String dosis = txtDosis.getText();
        String harga_jual = txtHargaJual.getText();
        String harga_beli = txtHargaBeli.getText();
        String tgl_exp = txtTglexp.getText();
        String ket = txtKet.getText();
        Obat obat = new Obat();
        Boolean tambah = obat.tambah(nama, jenis, kategori, stok, dosis, harga_beli, harga_jual, tgl_exp, ket);
        if(tambah){
            JOptionPane.showMessageDialog(rootPane, "Data berhasil di Simpan");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Data gagal di simpan");
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahObatAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnKembali;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextArea txtKet;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTglexp;
    // End of variables declaration//GEN-END:variables
}
