/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Logic.Obat;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.conn;

/**
 *
 * @author WINDOWS 10
 */
public class TambahDetailObatAdmin extends javax.swing.JFrame {

    /**
     * Creates new form TambahDetailObatAdmin
     */
    public TambahDetailObatAdmin() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setUndecorated(true);
        this.setVisible(true);
        setObat();
    }
    public void setObat(){
        try {
            ObatAdmin obat = new ObatAdmin();
            int kode_obat = obat.kd_obat;
            Connection koneksi = (Connection)conn.configDB();
            String queryCek = "SELECT * FROM obat WHERE kode_obat = '" + kode_obat +"'";
            Statement pstCek = koneksi.createStatement();
            ResultSet res = pstCek.executeQuery(queryCek);
            if(res.next()){
                lblKode.setText(res.getString("kode_obat"));
                lblNama.setText(res.getString("nama"));
                lblKategori.setText(res.getString("kategori"));
            }
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblKode = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        txtTglexp = new javax.swing.JTextField();
        cmbJenis = new javax.swing.JComboBox<>();
        txtDosis = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKet = new javax.swing.JTextArea();
        txtSimpan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 660, 150, 50);

        lblKode.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        getContentPane().add(lblKode);
        lblKode.setBounds(530, 130, 140, 30);

        lblKategori.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(lblKategori);
        lblKategori.setBounds(530, 250, 200, 30);

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        getContentPane().add(lblNama);
        lblNama.setBounds(530, 190, 200, 30);

        txtTglexp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTglexp.setBorder(null);
        getContentPane().add(txtTglexp);
        txtTglexp.setBounds(1080, 130, 250, 40);

        cmbJenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet", "Cair", "Kapsul", "Oles", "Suntik", "Implam" }));
        cmbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJenisActionPerformed(evt);
            }
        });
        getContentPane().add(cmbJenis);
        cmbJenis.setBounds(530, 320, 250, 40);

        txtDosis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDosis.setBorder(null);
        getContentPane().add(txtDosis);
        txtDosis.setBounds(530, 380, 250, 30);

        txtStok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtStok.setBorder(null);
        getContentPane().add(txtStok);
        txtStok.setBounds(1080, 190, 250, 30);

        txtHargaBeli.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHargaBeli.setBorder(null);
        getContentPane().add(txtHargaBeli);
        txtHargaBeli.setBounds(1090, 250, 240, 40);

        txtHargaJual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHargaJual.setBorder(null);
        getContentPane().add(txtHargaJual);
        txtHargaJual.setBounds(1090, 310, 240, 40);

        txtKet.setColumns(20);
        txtKet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtKet.setRows(5);
        txtKet.setBorder(null);
        jScrollPane1.setViewportView(txtKet);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 470, 800, 130);

        txtSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSimpanMouseClicked(evt);
            }
        });
        getContentPane().add(txtSimpan);
        txtSimpan.setBounds(530, 660, 150, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tambah detail obat.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 770);

        setBounds(0, 0, 1588, 914);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        ObatAdmin obat = new ObatAdmin();
        obat.kd_obat = 0;
        this.setVisible(false);
        obat.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void cmbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJenisActionPerformed

    private void txtSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSimpanMouseClicked
        String jenis = String.valueOf(cmbJenis.getSelectedItem());
        String stok = txtStok.getText();
        String dosis = txtDosis.getText();
        String harga_jual = txtHargaJual.getText();
        String harga_beli = txtHargaBeli.getText();
        String tgl_exp = txtTglexp.getText();
        String ket = txtKet.getText(); 
         
        try {
            ObatAdmin obat = new ObatAdmin();
            int kode_obat = obat.kd_obat;
            Connection koneksi = (Connection)conn.configDB();
            String queryCek = "SELECT * FROM obat WHERE kode_obat = '" + kode_obat +"'";
            Statement pstCek = koneksi.createStatement();
            ResultSet res = pstCek.executeQuery(queryCek);
            if(!res.next()){
                 return;
            }
             Obat o = new Obat();
                  boolean result = o.tambahDetail(res.getString("kode_obat"), jenis, dosis, stok, harga_jual, harga_beli, tgl_exp, ket);
                  if(result){
                      JOptionPane.showMessageDialog(rootPane, "Data berhasil ditambahkan");
                  }else{
                      JOptionPane.showMessageDialog(rootPane, "Data gagal ditambahkan");
                  }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_txtSimpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahDetailObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahDetailObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahDetailObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahDetailObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahDetailObatAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblKode;
    private javax.swing.JLabel lblNama;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextArea txtKet;
    private javax.swing.JLabel txtSimpan;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTglexp;
    // End of variables declaration//GEN-END:variables
}
