/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Logic.Obat;
import Logic.login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS 10
 */
public class TambahObatAdmin extends javax.swing.JFrame {
login lg = new login();
    /**
     * Creates new form TambahObatAdmin
     */
    public TambahObatAdmin() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setUndecorated(true);
        this.setVisible(true);
        lblNama.setText(lg.nama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKembali = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtDosis = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        txtTglexp = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbJenis = new javax.swing.JComboBox<>();
        cmbKategori = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKet = new javax.swing.JTextArea();
        cmbUser = new javax.swing.JComboBox<>();
        lblNama = new javax.swing.JLabel();
        btnTransaksi = new javax.swing.JLabel();
        btnLaporan = new javax.swing.JLabel();
        btnPengguna = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JLabel();
        btnObat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });
        getContentPane().add(btnKembali);
        btnKembali.setBounds(350, 590, 150, 40);

        txtStok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtStok.setBorder(null);
        txtStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStokKeyPressed(evt);
            }
        });
        getContentPane().add(txtStok);
        txtStok.setBounds(1080, 190, 250, 30);

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNama.setBorder(null);
        getContentPane().add(txtNama);
        txtNama.setBounds(530, 130, 250, 40);

        txtDosis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDosis.setBorder(null);
        getContentPane().add(txtDosis);
        txtDosis.setBounds(530, 320, 250, 40);

        txtHargaJual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHargaJual.setBorder(null);
        getContentPane().add(txtHargaJual);
        txtHargaJual.setBounds(1080, 310, 250, 40);

        txtTglexp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTglexp.setBorder(null);
        getContentPane().add(txtTglexp);
        txtTglexp.setBounds(1080, 130, 250, 40);

        txtHargaBeli.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHargaBeli.setBorder(null);
        getContentPane().add(txtHargaBeli);
        txtHargaBeli.setBounds(1080, 250, 250, 40);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 590, 150, 40);

        cmbJenis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet", "Cair", "Kapsul", "Oles", "Suntik", "Implam" }));
        getContentPane().add(cmbJenis);
        cmbJenis.setBounds(520, 260, 260, 30);

        cmbKategori.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Obat BebasTerbatas", "Obat Bebas", "Obat Keras", "Obat Wajib Apotek", "Obat Gol Narkotika", "Obat Psikotropika", "Obat Herbal", " " }));
        getContentPane().add(cmbKategori);
        cmbKategori.setBounds(520, 200, 260, 30);

        txtKet.setColumns(20);
        txtKet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtKet.setRows(5);
        txtKet.setBorder(null);
        jScrollPane1.setViewportView(txtKet);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 390, 800, 140);

        cmbUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Menu----", "Profil", "Logout" }));
        cmbUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserActionPerformed(evt);
            }
        });
        getContentPane().add(cmbUser);
        cmbUser.setBounds(1140, 50, 130, 26);

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNama.setText("jLabel2");
        getContentPane().add(lblNama);
        lblNama.setBounds(1140, 10, 130, 30);

        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
        });
        getContentPane().add(btnTransaksi);
        btnTransaksi.setBounds(10, 300, 250, 50);

        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
        });
        getContentPane().add(btnLaporan);
        btnLaporan.setBounds(20, 450, 250, 60);

        btnPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPenggunaMouseClicked(evt);
            }
        });
        getContentPane().add(btnPengguna);
        btnPengguna.setBounds(10, 370, 250, 60);

        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });
        getContentPane().add(btnDashboard);
        btnDashboard.setBounds(10, 150, 250, 50);

        btnObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnObatMouseClicked(evt);
            }
        });
        getContentPane().add(btnObat);
        btnObat.setBounds(10, 220, 250, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tambahobat.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        setBounds(0, 0, 1601, 888);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        ObatAdmin obat = new ObatAdmin();
        obat.kd_obat = 0;
        this.setVisible(false);
        obat.setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        String nama = txtNama.getText();
        String jenis = String.valueOf(cmbJenis.getSelectedItem());
        String kategori = String.valueOf(cmbKategori.getSelectedItem());
        String stok = txtStok.getText();
        String dosis = txtDosis.getText();
        String harga_jual = txtHargaJual.getText();
        String harga_beli = txtHargaBeli.getText();
        String tgl_exp = txtTglexp.getText();
        String ket = txtKet.getText();
        Obat obat = new Obat();
        Boolean tambah = obat.tambah(nama, jenis, kategori, stok, dosis, harga_beli, harga_jual, tgl_exp, ket);
        if(tambah){
            JOptionPane.showMessageDialog(rootPane, "Data berhasil di Simpan");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Data gagal di simpan");
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void cmbUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserActionPerformed
        String menu = String.valueOf(cmbUser.getSelectedItem());
        switch(menu){
            case "Profil":
            this.setVisible(false);
            this.dispose();
            new ProfilUser().setVisible(true);
            break;
            case "Logout":
            this.setVisible(false);
            this.dispose();
            lg.logOut();
            break;
        }
    }//GEN-LAST:event_cmbUserActionPerformed

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        this.setVisible(false);
        this.dispose();
        new TransaksiAdmin().setVisible(true);
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
        this.setVisible(false);
        this.dispose();
        new LaporanAdmin().setVisible(true);
    }//GEN-LAST:event_btnLaporanMouseClicked

    private void btnPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPenggunaMouseClicked
        this.setVisible(false);
        this.dispose();
        new PenggunaAdmin().setVisible(true);
    }//GEN-LAST:event_btnPenggunaMouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        this.setVisible(false);
        this.dispose();
        new DashboardAdmin().setVisible(true);
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnObatMouseClicked
        this.setVisible(false);
        this.dispose();
        new ObatAdmin().setVisible(true);
    }//GEN-LAST:event_btnObatMouseClicked

    private void txtStokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStokKeyPressed
        String value = txtStok.getText();
        int i = value.length();
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9'){
            txtStok.setEditable(true);
        }else{
            txtStok.setEditable(false);
            JOptionPane.showMessageDialog(rootPane, "masukan input dalam bentuk integer");
        }
    }//GEN-LAST:event_txtStokKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahObatAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahObatAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnKembali;
    private javax.swing.JLabel btnLaporan;
    private javax.swing.JLabel btnObat;
    private javax.swing.JLabel btnPengguna;
    private javax.swing.JLabel btnTransaksi;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JComboBox<String> cmbUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNama;
    private javax.swing.JTextField txtDosis;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextArea txtKet;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTglexp;
    // End of variables declaration//GEN-END:variables
}